name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install needed software
        run: ./.github/scripts/Install.ps1
        shell: pwsh
      - name: Build Crescendo module
        run: ./build.ps1
        shell: pwsh
      - name: Publish PowerShell Module
        run: ./.github/scripts/Deploy.ps1
        shell: pwsh
        env:
          POWERSHELLGALLERY_APIKEY: ${{ secrets.POWERSHELLGALLERY_APIKEY }}
          GITHUB_PRERELEASE: ${{ github.event.release.prerelease }}
